/**
 * Access-related Env members (story 1.4).
 *
 * Hand-authored, deliberately NOT in env.d.ts: that file is generated by
 * `wrangler types env.d.ts` from wrangler.jsonc bindings and is overwritten
 * wholesale on every regeneration. None of these values live in wrangler.jsonc:
 *
 *   TEAM_DOMAIN / POLICY_AUD / OPERATOR_EMAIL
 *     Wrangler secrets, set per environment in story 1.5. Staging and
 *     production get DIFFERENT POLICY_AUD values — the AUD tag is per Access
 *     application.
 *
 *   OPERATOR_DISPLAY_NAME
 *     Public-safe name for the admin session strip and, later, the public
 *     mode-change audit on ops. Not secret, but not a wrangler.jsonc var
 *     either — it belongs with the identity it names.
 *
 *   ACCESS_DEV_BYPASS
 *     Local development only. Lives in .dev.vars, which is gitignored
 *     (`.dev.vars*`) and read only by `wrangler dev` — never bundled, never
 *     deployed. Keeping it out of wrangler.jsonc is what makes it impossible
 *     to ship enabled.
 *
 * `interface Env` is declared globally by env.d.ts, so these merge into it.
 * All optional: absent at runtime is a real state, and verifyOperator must
 * fail closed on it rather than assume presence.
 */

interface Env {
  /** e.g. https://<team-name>.cloudflareaccess.com — secret. */
  TEAM_DOMAIN?: string;
  /** Access application Audience (AUD) tag — secret, per environment. */
  POLICY_AUD?: string;
  /** The single authorized operator identity — secret. */
  OPERATOR_EMAIL?: string;
  /** Public-safe display name. Defaults to "Patrick". */
  OPERATOR_DISPLAY_NAME?: string;
  /** Exactly "true" enables the local bypass. .dev.vars only. */
  ACCESS_DEV_BYPASS?: string;
}
