/**
 * D1 binding (Story 2.1).
 *
 * `env.d.ts` is regenerated by `wrangler types` from wrangler.jsonc. At the
 * last generation the D1 block existed in config but was not reflected here
 * (hash predates Story 2.1). Until the next `wrangler types` run, this merge
 * declaration keeps `env.DB` typed. Safe to delete once regeneration includes
 * `DB: D1Database`.
 */
interface Env {
  DB: D1Database;
}
